# Generated by Django 4.1.1 on 2022-09-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('cod_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_cargo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CarreiraModel',
            fields=[
                ('cod_carreira', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_carreira', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_categoria', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('cod_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_empresa', models.CharField(max_length=300)),
                ('sigla_empresa', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='LotacaoModel',
            fields=[
                ('cod_lotacao', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_lotacao', models.CharField(max_length=300)),
                ('data_inicio', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=320)),
                ('tipo_sanguinio', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=9)),
                ('estado_civil', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_vinculo', models.IntegerField()),
                ('tipo_vinculo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('carga_horaria', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cargomodel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.categoriamodel')),
                ('lotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lotacaomodel')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pessoamodel')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinculomodel')),
            ],
        ),
        migrations.AddField(
            model_name='cargomodel',
            name='carreira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.carreiramodel'),
        ),
    ]
