# Generated by Django 4.1.1 on 2022-09-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoamodel',
            old_name='tipo_sanguinio',
            new_name='tipo_sanguineo',
        ),
    ]
